//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Provetex
{
    using System;
    using System.Collections.Generic;
    
    public partial class chique
    {
        public int C_numero_chique { get; set; }
        public Nullable<int> C_bon { get; set; }
        public Nullable<decimal> C_prix_chique { get; set; }
        public Nullable<System.DateTime> C_date_chique { get; set; }
    
        public virtual bon bon { get; set; }
    }
}
